/** Font Awesome 6 free solid ikonu saraksts (kā FS dashboard.php). */

export const FA_ICONS_ALL: string[] = [
  "fa-solid fa-film",
  "fa-solid fa-music",
  "fa-solid fa-headphones-simple",
  "fa-solid fa-radio",
  "fa-solid fa-podcast",
  "fa-solid fa-tv",
  "fa-solid fa-clapperboard",
  "fa-solid fa-video",
  "fa-solid fa-cloud",
  "fa-solid fa-briefcase",
  "fa-solid fa-newspaper",
  "fa-solid fa-book",
  "fa-solid fa-bookmark",
  "fa-solid fa-gamepad",
  "fa-solid fa-chess",
  "fa-solid fa-dice-d6",
  "fa-solid fa-puzzle-piece",
  "fa-solid fa-box",
  "fa-solid fa-cube",
  "fa-solid fa-gift",
  "fa-solid fa-shield-halved",
  "fa-solid fa-lock",
  "fa-solid fa-key",
  "fa-solid fa-envelope",
  "fa-solid fa-paper-plane",
  "fa-solid fa-inbox",
  "fa-solid fa-globe",
  "fa-solid fa-wifi",
  "fa-solid fa-rss",
  "fa-solid fa-link",
  "fa-solid fa-lightbulb",
  "fa-solid fa-bolt",
  "fa-solid fa-plug",
  "fa-solid fa-battery-full",
  "fa-solid fa-dumbbell",
  "fa-solid fa-heart-pulse",
  "fa-solid fa-palette",
  "fa-solid fa-paintbrush",
  "fa-solid fa-pen",
  "fa-solid fa-image",
  "fa-solid fa-camera",
  "fa-solid fa-wrench",
  "fa-solid fa-hammer",
  "fa-solid fa-screwdriver-wrench",
  "fa-solid fa-house",
  "fa-solid fa-building",
  "fa-solid fa-building-columns",
  "fa-solid fa-store",
  "fa-solid fa-landmark",
  "fa-solid fa-hospital",
  "fa-solid fa-school",
  "fa-solid fa-car",
  "fa-solid fa-bus",
  "fa-solid fa-train",
  "fa-solid fa-plane",
  "fa-solid fa-ship",
  "fa-solid fa-bicycle",
  "fa-solid fa-mug-hot",
  "fa-solid fa-utensils",
  "fa-solid fa-cake-candles",
  "fa-solid fa-pizza-slice",
  "fa-solid fa-burger",
  "fa-solid fa-cart-shopping",
  "fa-solid fa-bag-shopping",
  "fa-solid fa-credit-card",
  "fa-solid fa-money-bill-wave",
  "fa-solid fa-coins",
  "fa-solid fa-chart-line",
  "fa-solid fa-chart-pie",
  "fa-solid fa-mobile-screen-button",
  "fa-solid fa-laptop",
  "fa-solid fa-desktop",
  "fa-solid fa-tablet-screen-button",
  "fa-solid fa-keyboard",
  "fa-solid fa-computer-mouse",
  "fa-solid fa-print",
  "fa-solid fa-user",
  "fa-solid fa-users",
  "fa-solid fa-user-group",
  "fa-solid fa-paw",
  "fa-solid fa-fish",
  "fa-solid fa-dove",
  "fa-solid fa-leaf",
  "fa-solid fa-tree",
  "fa-solid fa-seedling",
  "fa-solid fa-sun",
  "fa-solid fa-moon",
  "fa-solid fa-cloud-sun",
  "fa-solid fa-star",
  "fa-solid fa-fire",
  "fa-solid fa-snowflake",
  "fa-solid fa-shirt",
  "fa-solid fa-socks",
  "fa-solid fa-bell",
  "fa-solid fa-calendar-days",
  "fa-solid fa-clock",
  "fa-solid fa-map-location-dot",
  "fa-solid fa-location-dot",
  "fa-solid fa-receipt",
  "fa-solid fa-file-invoice-dollar",
  "fa-solid fa-clipboard",
  "fa-solid fa-note-sticky",
];

export const FS_COLOR_DOTS = [
  "#0d9488",
  "#e50914",
  "#1db954",
  "#ea4c89",
  "#f59e0b",
  "#3b82f6",
  "#059669",
  "#ef4444",
  "#64748b",
  "#0ea5e9",
];
